services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-encurtador-url
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_HOST=mongo
      - MONGO_DB=encurta_db
      - MONGO_USER=root
      - MONGO_PASS=rootpassword
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: encurta_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: